../common/cpu_defs.sv
../core/pipeline/if_id_reg.sv
../core/decode/regfile.sv
../core/decode/load_hazard_ctrl.sv
../core/decode/forwarding.sv
../core/decode/alu_src_mux.sv
../core/pipeline/id_ex_payload_builder.sv
../core/pipeline/id_ex_reg.sv
../core/pipeline/id_ex_reg_s1.sv
../core/execute/alu.sv
../core/execute/branch_condition.sv
../core/decode/id_stage_derive.sv
../core/execute/ex_stage_ctrl.sv
../core/frontend/predictor_resolve_builder.sv
../core/frontend/predictor_update_ctrl.sv
../core/execute/branch_unit.sv
../core/frontend/frontend_stage1_direction.sv
../core/frontend/frontend_abtb.sv
../core/frontend/observe/frontend_abtb_monitor_adapter.sv
../core/frontend/observe/frontend_abtb_monitor.sv
../core/frontend/frontend_f0_packet_builder.sv
../core/frontend/frontend_pair_policy.sv
../core/frontend/frontend_stage1_steer_ctrl.sv
../core/frontend/frontend_fetch_state.sv
../core/frontend/frontend_fetch_queue.sv
../core/frontend/frontend_abtb_sidecar.sv
../core/frontend/frontend_ftq.sv
../core/lsu/mem_interface.sv
../core/control/redirect_ctrl.sv
../core/control/timer_irq_ctrl.sv
../core/lsu/memory_access_unit.sv
../core/execute/muldiv_unit.sv
../core/dual_issue_counter.sv
../core/pipeline/ex_mem_payload_builder.sv
../core/pipeline/ex_mem_reg.sv
../core/pipeline/ex_mem_reg_s1.sv
../core/pipeline/mem_wb_payload_builder.sv
../core/pipeline/mem_wb_reg.sv
../core/pipeline/mem_wb_reg_s1.sv
../core/wb_mux.sv
